<?php

/**
 * PluginsfUserNote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    AmericanHealthPlans
 * @subpackage lib
 * @author     Stephen Ostrow <sostrow@sowebdesigns.com>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class PluginsfUserNote extends BasesfUserNote
{

}