<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserEmailAddress extends BasesfUserEmailAddress
{

  /**
   * This returns the email address for the object
   *
   * @return string
   */
  public function __toString()
  {
    return $this['address'];
  }

}
