<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserState extends BasesfUserState
{

  /**
   * This returns a formatted state name
   *
   * @return string
   */
  public function __toString()
  {
    return ucwords(strtolower($this->name));
  }

}
