<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserImAccount extends BasesfUserImAccount
{

  /**
   * This returns a formatted instant messaging string with protocol type
   *
   * @return string
   */
  public function __toString()
  {
    return $this['ImAccountType'] . ":// " . $this['nickname'];
  }

}
