<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/30 12:01:38
?>
<?php echo form_tag('sfGuardModules/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_guard_modules, 'getid') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_guard_modules[module_name]', __($labels['sf_guard_modules{module_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{module_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{module_name}')): ?>
    <?php echo form_error('sf_guard_modules{module_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_modules, array (
  0 => 'get',
  1 => 
  array (
    0 => 'module_name',
  ),
), array (
  'control_name' => 'sf_guard_modules[module_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_modules[action_name]', __($labels['sf_guard_modules{action_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{action_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{action_name}')): ?>
    <?php echo form_error('sf_guard_modules{action_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_modules, array (
  0 => 'get',
  1 => 
  array (
    0 => 'action_name',
  ),
), array (
  'control_name' => 'sf_guard_modules[action_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_modules[is_secure]', __($labels['sf_guard_modules{is_secure}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{is_secure}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{is_secure}')): ?>
    <?php echo form_error('sf_guard_modules{is_secure}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($sf_guard_modules, array (
  0 => 'get',
  1 => 
  array (
    0 => 'is_secure',
  ),
), array (
  'control_name' => 'sf_guard_modules[is_secure]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_information" class="">
<h2><?php echo __('Information') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_modules[created_at]', __($labels['sf_guard_modules{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{created_at}')): ?>
    <?php echo form_error('sf_guard_modules{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_modules->created_at !== null && $sf_guard_modules->created_at !== '') ? format_date($sf_guard_modules->created_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_modules[updated_at]', __($labels['sf_guard_modules{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{updated_at}')): ?>
    <?php echo form_error('sf_guard_modules{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_modules->updated_at !== null && $sf_guard_modules->updated_at !== '') ? format_date($sf_guard_modules->updated_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>


<fieldset id="sf_fieldset_permissions_and_groups" class="">
<h2><?php echo __('Permissions and Groups') ?></h2>

<?php if(count($sf_guard_modules->groups) > 0): ?>
<div class="form-row">
  <?php echo label_for('sf_guard_modules[groups]', __($labels['sf_guard_modules{groups}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{groups}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{groups}')): ?>
    <?php echo form_error('sf_guard_modules{groups}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_doctrine_admin_check_list($sf_guard_modules, array (
  0 => 'get',
  1 => 
  array (
    0 => 'groups',
  ),
), array (
  'control_name' => 'sf_guard_modules[groups]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
<?php endif;?>

<div class="form-row">
  <?php echo label_for('sf_guard_modules[permissions]', __($labels['sf_guard_modules{permissions}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_modules{permissions}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_modules{permissions}')): ?>
    <?php echo form_error('sf_guard_modules{permissions}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_doctrine_admin_check_list($sf_guard_modules, array (
  0 => 'get',
  1 => 
  array (
    0 => 'permissions',
  ),
), array (
  'control_name' => 'sf_guard_modules[permissions]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('sf_guard_modules' => $sf_guard_modules)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($sf_guard_modules->id): ?>
<?php echo button_to(__('delete'), 'sfGuardModules/delete?id='.$sf_guard_modules->id, array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
