<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/30 10:55:45
?>
<?php use_helper('I18N', 'Date') ?>


<div class="deal"><?php echo __('User Login list', 
array()) ?></div>


<?php include_partial('sfGuardUserLogin/list_header', array('pager' => $pager)) ?>

<?php include_partial('filters', array('filters' => $filters)) ?>

<br />
<br />



<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('sfGuardUserLogin/list', array('pager' => $pager)) ?>
<?php endif; ?>

<?php include_partial('sfGuardUserLogin/list_footer', array('pager' => $pager)) ?>
