default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [ style, http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css ]

  javascripts:    []

  has_layout:     on
  layout:         layout
