<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:24
?>
<?php use_helper('ObjectDoctrineAdmin', 'Object', 'Date') ?>

<?php echo form_tag('reservation/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($hotels_reservation, 'getid') ?>


<table>
<tbody>
<tr>
  <th>Hotels client: </th>
  <td><?php echo object_select_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'client_id',
  ),
), array (
  'related_class' => 'HotelsClient',
  'control_name' => 'hotels_reservation[HotelsClient]',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Hotels room type: </th>
  <td><?php echo object_select_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'room_id',
  ),
), array (
  'related_class' => 'HotelsRoomType',
  'control_name' => 'hotels_reservation[HotelsRoomType]',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Total: </th>
  <td><?php echo object_input_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'total',
  ),
), array (
  'size' => 7,
  'control_name' => 'hotels_reservation[total]',
)) ?></td>
</tr>
<tr>
  <th>Hash: </th>
  <td><?php echo object_input_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'hash',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_reservation[hash]',
)) ?></td>
</tr>
<tr>
  <th>Reserved from: </th>
  <td><?php echo object_input_date_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'reserved_from',
  ),
), array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'hotels_reservation[reserved_from]',
)) ?></td>
</tr>
<tr>
  <th>Reserved to: </th>
  <td><?php echo object_input_date_tag($hotels_reservation, array (
  0 => 'get',
  1 => 
  array (
    0 => 'reserved_to',
  ),
), array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'hotels_reservation[reserved_to]',
)) ?></td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($hotels_reservation->id): ?>
  &nbsp;<?php echo link_to('delete', 'reservation/delete?id='.$hotels_reservation->id, 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'reservation/show?id='.$hotels_reservation->id) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'reservation/list') ?>
<?php endif; ?>
</form>
