<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:24
?>
<h1>reservation</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>HotelsClient</th>
  <th>HotelsRoomType</th>
  <th>Total</th>
  <th>Hash</th>
  <th>Reserved from</th>
  <th>Reserved to</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($hotels_reservations as $hotels_reservation): ?>
<tr>
    <td><?php echo link_to($hotels_reservation->get('id'), 'reservation/show?id='.$hotels_reservation->id); ?></td>
      <td><?php echo $hotels_reservation->get('HotelsClient'); ?></td>
      <td><?php echo $hotels_reservation->get('HotelsRoomType'); ?></td>
      <td><?php echo $hotels_reservation->get('total'); ?></td>
      <td><?php echo $hotels_reservation->get('hash'); ?></td>
      <td><?php echo $hotels_reservation->get('reserved_from'); ?></td>
      <td><?php echo $hotels_reservation->get('reserved_to'); ?></td>
      <td><?php echo $hotels_reservation->get('created_at'); ?></td>
      <td><?php echo $hotels_reservation->get('updated_at'); ?></td>
  </tr>
<?php endforeach; ?>
<tr><td>Number of hotels_reservations: <?php echo count($hotels_reservations) ?></td></tr>
</tbody>
</table>

<?php echo link_to ('create', 'reservation/create') ?>
