<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:24
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $hotels_reservation->getid() ?></td>
</tr>
<tr>
<th>Hotels client: </th>
<td><?php echo $hotels_reservation->getHotelsClient() ?></td>
</tr>
<tr>
<th>Hotels room type: </th>
<td><?php echo $hotels_reservation->getHotelsRoomType() ?></td>
</tr>
<tr>
<th>Total: </th>
<td><?php echo $hotels_reservation->gettotal() ?></td>
</tr>
<tr>
<th>Hash: </th>
<td><?php echo $hotels_reservation->gethash() ?></td>
</tr>
<tr>
<th>Reserved from: </th>
<td><?php echo $hotels_reservation->getreserved_from() ?></td>
</tr>
<tr>
<th>Reserved to: </th>
<td><?php echo $hotels_reservation->getreserved_to() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $hotels_reservation->getcreated_at() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $hotels_reservation->getupdated_at() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'reservation/edit?id='.$hotels_reservation->id) ?>
&nbsp;<?php echo link_to('list', 'reservation/list') ?>
