<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */



class HotelsRoomTable extends Doctrine_Table{
    
    private static function getAllRoom(){
        
        use_helper('MoneyConvertor');
        
        $room_list = array();
        $room_numbers = Doctrine::getTable('HotelsRoom')->findAll();
        foreach($room_numbers as $room_number){
            $room_info[$room_number->id] = array($room_number->number . ' - ' 
                . $room_number->HotelsRoomType->type . ' - ' 
                . convertFromCents($room_number->price) 
                . sfConfig::get('app_currency_sign'), 
                $room_number->price) ;
        }
        return $room_info;
    }
    
    public static function getRoomList(){
        
        use_helper('MoneyConvertor');
        
        $room_list = array();
        $room_numbers = Doctrine::getTable('HotelsRoom')->findAll();
        foreach($room_numbers as $room_number){
            $room_info['list'][$room_number->id] = $room_number->number . ' - ' 
                . $room_number->HotelsRoomType->type . ' - ' 
                . convertFromCents($room_number->price) 
                . sfConfig::get('app_currency_sign');
            $room_info['price'][$room_number->id] = $room_number->price;
        }
        return $room_info;
    }
}