<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelsRoomTypeTable extends Doctrine_Table{
    public static function getRoomTypeList(){
        $type_list = array();
        $room_types = Doctrine::getTable('HotelsRoomType')->findAll();
        foreach($room_types as $room_type){
            $type_list[$room_type->id] = $room_type->type;
        }
        return $type_list;
    }
}