<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelsRoomTable extends Doctrine_Table{
    public static function getRoomList(){
        $room_list = array();
        $room_numbers = Doctrine::getTable('HotelsRoom')->findAll();
        foreach($room_numbers as $room_number){
            $room_list[$room_number->id] = $room_number->number;
        }
        return $room_list;
    }
}