<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelsRoom extends BaseHotelsRoom{
    public function getFormattedPrice(){
        return sprintf(sfConfig::get('app_money_format'), $this->getPrice()/100);
    }
    
    public function getRoomType(){
        $room_type = Doctrine::getTable('HotelsRoomType')->find($this->getId());
        return $room_type->get('type');
    }
}
