# default rules
homepage:
  url:   /
  param: { module: room, action: index }

make_order:
  url:   /make_order
  param: { module: order, action: makeOrder}

show_room:
  url:   /room/show/:id
  param: { module: room, action: show }  
  
logout:
  url:   /logout
  param: { module: authentication, action: logout }

login:
  url:   /login
  param: { module: authentication, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
