default:
  http_metas:
    content-type: text/html

  metas:
    title:        Hello world
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    
    -style 
    -http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css

  javascripts:    
    -jquery-1.9.0.min.js
    -http://code.jquery.com/ui/1.10.0/jquery-ui.js

  has_layout:     on
  layout:         layout
