default:
  http_metas:
    content-type: text/html

  metas:
    title:        Hello world
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [style]

  javascripts:    [jquery-1.9.0.min.js]

  has_layout:     on
  layout:         layout
