<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:19
?>
<?php use_helper('ObjectDoctrineAdmin', 'Object', 'Date') ?>

<?php echo form_tag('room_type/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($hotels_room_type, 'getid') ?>


<table>
<tbody>
<tr>
  <th>Type: </th>
  <td><?php echo object_input_tag($hotels_room_type, array (
  0 => 'get',
  1 => 
  array (
    0 => 'type',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_room_type[type]',
)) ?></td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($hotels_room_type->id): ?>
  &nbsp;<?php echo link_to('delete', 'room_type/delete?id='.$hotels_room_type->id, 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'room_type/show?id='.$hotels_room_type->id) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'room_type/list') ?>
<?php endif; ?>
</form>
