<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:19
?>
<h1>room_type</h1>
<?php if($massage): ?>
    <?php echo $massage ?>
<?php endif; ?>
<table>
<thead>
<tr>
  <th>Id</th>
  <th>Type</th>
  <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($hotels_room_types as $hotels_room_type): ?>
<tr>
    <td><?php echo link_to($hotels_room_type->get('id'), 'room_type/show?id='.$hotels_room_type->id); ?></td>
      <td><?php echo $hotels_room_type->get('type'); ?></td>
      <td><?php echo link_to ('delete', 'room_type/delete?id='.$hotels_room_type->id) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'room_type/create') ?>
