generator:
  class: sfDoctrineAdminGenerator
  param:
    model_class: HotelsRoom
    list:
      title: Rooms
      display: [ id, HotelsRoomType.type , _price_list  ]
      filters: [ _type_id, price ]
      fields:
        HotelsRoomType:
          type:
            name: Room type
      max_per_page: 10
      object_actions:
        _edit: ~
        show: 
          name: Show
          action: show
          icon: /sf/sf_admin/images/default_icon.png
        _delete: ~
    edit:
      title: Editing room "%%id%%"
      display: [ _type_id, price, photo ]
      