<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:52
?>
<?php use_helper('ObjectDoctrineAdmin', 'Object', 'Date') ?>

<?php echo form_tag('client/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($hotels_client, 'getid') ?>


<table>
<tbody>
<tr>
  <th>First name: </th>
  <td><?php echo object_input_tag($hotels_client, array (
  0 => 'get',
  1 => 
  array (
    0 => 'first_name',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_client[first_name]',
)) ?></td>
</tr>
<tr>
  <th>Last name: </th>
  <td><?php echo object_input_tag($hotels_client, array (
  0 => 'get',
  1 => 
  array (
    0 => 'last_name',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_client[last_name]',
)) ?></td>
</tr>
<tr>
  <th>Email: </th>
  <td><?php echo object_input_tag($hotels_client, array (
  0 => 'get',
  1 => 
  array (
    0 => 'email',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_client[email]',
)) ?></td>
</tr>
<tr>
  <th>Phone: </th>
  <td><?php echo object_input_tag($hotels_client, array (
  0 => 'get',
  1 => 
  array (
    0 => 'phone',
  ),
), array (
  'size' => 80,
  'control_name' => 'hotels_client[phone]',
)) ?></td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($hotels_client->id): ?>
  &nbsp;<?php echo link_to('delete', 'client/delete?id='.$hotels_client->id, 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'client/show?id='.$hotels_client->id) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'client/list') ?>
<?php endif; ?>
</form>
