<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:52
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $hotels_client->getid() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $hotels_client->getfirst_name() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $hotels_client->getlast_name() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $hotels_client->getemail() ?></td>
</tr>
<tr>
<th>Phone: </th>
<td><?php echo $hotels_client->getphone() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $hotels_client->getcreated_at() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $hotels_client->getupdated_at() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'client/edit?id='.$hotels_client->id) ?>
&nbsp;<?php echo link_to('list', 'client/list') ?>
