<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:52
?>
<?php

/**
 * client actions.
 *
 * @package    sf_sandbox
 * @subpackage client
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Olivier Verdier <Olivier.Verdier@gmail.com>
 * @version    SVN: $Id: actions.class.php 5639 2007-10-23 14:27:18Z Eric.Fredj $
 */
class clientActions extends autoclientActions{
    public function addFiltersCriteria($q){
        parent::addFiltersCriteria($q);
        if(isset($this->filters['email']) && $this->filters['email'] !== ''){
            $q->addWhere("HotelsClient.email LIKE ?", "%{$this->filters['email']}%");
        }
    }
    
    public function validateClientEmail(){
        return true;
    }
    
    public function executeShow(){
        $client_id = (int) $this->getRequestParameter('id', 0);
        if(empty($client_id)){
            $this->setFlash('warning', 'Invalid client id specified');
            $this->redirect('client');
        }
        $this->hotels_client = Doctrine::getTable('HotelsClient')->find($client_id);
    }
    
    public function executeGetEmailList(){
        $email_list = array();
        $email = preg_replace('/[^\w@\.\-]+/i', '', $this->getRequestParameter('term'));
        
        $client_emails = Doctrine_Manager::connection()
            ->fetchAll('SELECT id, email FROM hotels_client WHERE email LIKE ?', array("%$email%"));
        
        foreach($client_emails as $client_email){
            $email_list[] = array('label' => $client_email['email'], 
                'value' => $client_email['id']);
        }
        
        $this->renderText(json_encode($email_list));
        return sfView::NONE;
    }
}
