<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:08
?>
<?php

/**
 * room actions.
 *
 * @package    sf_sandbox
 * @subpackage room
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Olivier Verdier <Olivier.Verdier@gmail.com>
 * @version    SVN: $Id: actions.class.php 5639 2007-10-23 14:27:18Z Eric.Fredj $
 */
class roomActions extends autoroomActions{
    public function executeShow(){
        $room_id = (int) $this->getRequestParameter('id', 0);
        if(empty($room_id)){
            $this->setFlash('error', 'Invalid room id specified');
            $this->redirect('room');
        }
        $this->hotels_room = Doctrine::getTable('HotelsRoom')->find($room_id);
    }
}