#all:
#  propel:
#    class:      sfPropelDatabase
#    param:
#      phptype:  sqlite
#      database: %SF_DATA_DIR%/sandbox.db

all:
  propel:
    class:      sfDoctrineDatabase
    param:
      dns: sqlite:///<?php echo dirname(__FILE__); ?>/doctrine.db