#all:
#  propel:
#    class:      sfPropelDatabase
#    param:
#      phptype:  sqlite
#      database: %SF_DATA_DIR%/sandbox.db

all:
  propel:
    class:      sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=doctrine_hotels'
      username: root
      password: ''