<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/29 17:22:31
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'sfGuardUserLog/list?id='.$sf_guard_user_log->id.'&user_id='.$sf_guard_user_log->user_id, array (
  'class' => 'sf_admin_action_list',
)) ?></li>
</ul>
