<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/29 17:22:31
?>
<?php echo form_tag('sfGuardUserLog/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_guard_user_log, 'getid') ?>
<?php echo object_input_hidden_tag($sf_guard_user_log, 'getuser_id') ?>

<fieldset id="sf_fieldset_information" class="">
<h2><?php echo __('Information') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_user_log[created_at]', __($labels['sf_guard_user_log{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user_log{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user_log{created_at}')): ?>
    <?php echo form_error('sf_guard_user_log{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user_log->created_at !== null && $sf_guard_user_log->created_at !== '') ? format_date($sf_guard_user_log->created_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user_log[url]', __($labels['sf_guard_user_log{url}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user_log{url}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user_log{url}')): ?>
    <?php echo form_error('sf_guard_user_log{url}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

	<?=$sf_guard_user_log->url?>  
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user_log[module_name]', __($labels['sf_guard_user_log{module_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user_log{module_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user_log{module_name}')): ?>
    <?php echo form_error('sf_guard_user_log{module_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>
  
	<?=$sf_guard_user_log->module_name?>  
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user_log[action_name]', __($labels['sf_guard_user_log{action_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user_log{action_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user_log{action_name}')): ?>
    <?php echo form_error('sf_guard_user_log{action_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>
  
<?=$sf_guard_user_log->action_name?>  
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user_log[parameter]', __($labels['sf_guard_user_log{parameter}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user_log{parameter}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user_log{parameter}')): ?>
    <?php echo form_error('sf_guard_user_log{parameter}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

	<pre>
		<?php 
		if(defined('SF_GUARD_USER_LOG_PATH') && SF_GUARD_USER_LOG_PATH){
			$parameter = file_get_contents($sf_guard_user_log->parameter);
		}else{
			$parameter = $sf_guard_user_log->parameter;
		}
		
		echo htmlspecialchars(print_r(unserialize($parameter), 1)); 
		?>
	</pre>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('sf_guard_user_log' => $sf_guard_user_log)) ?>

</form>


