<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/30 11:26:57
?>
<script type="text/javascript">
$(document).ready(function(){
    $(".btn-slide").click(function(){
        $("#panel").slideToggle("slow");
        $(this).toggleClass("active"); return false;
    });
});
</script>

<?php use_helper('Object') ?>

<!--* Filters *-->
<div id="admin_new_container_br">
<table cellspacing="0" width="100%" class="sf_admin_list" style="border-left-style:solid; border-left-width:1px; border-left-color:#c0cbd8; border-top-style:solid; border-top-width:1px; border-top-color:#c0cbd8; border-right-style:solid; border-right-width:1px; border-right-color:#c0cbd8; border-bottom-style:solid; border-bottom-width:1px; border-bottom-color:#c0cbd8;">
<thead>
<tr width="100%">
<?php echo form_tag('sfGuardUserLog/list', array('method' => 'get')) ?>

  <th id="filt" width="100%"><a href="" class="btn-slide"><?php echo __('Filters') ?><img src="/images/admin/open.png"></a></th>

</tr>
</thead>
</table>
<div id="panel" style="display: none;">
<table cellspacing="0" border="0" class="sf_admin_list">
<thead>
<tr class="sf_admin_row_br_0_0" width="100%">

        <td><label for="filters_user_id"><?php echo __('User Id:') ?></label></td>
        
        <td>

 <?php echo input_tag('filters[user_id]', isset($filters['user_id']) ? $filters['user_id'] : null, array (
  'size' => 15,
)) ?>
            
        </td>
               


        <td><label for="filters_email"><?php echo __('Email:') ?></label></td>
        
        <td>
            <?php echo input_tag('filters[email]', isset($filters['email']) ? $filters['email'] : null, array (
  'size' => 15,
)) ?>
            
        </td>
               


        <td><label for="filters_module_name"><?php echo __('Module name:') ?></label></td>
        
        <td>
            <?php echo input_tag('filters[module_name]', isset($filters['module_name']) ? $filters['module_name'] : null, array (
  'size' => 15,
)) ?>
            
        </td>
               


        <td><label for="filters_action_name"><?php echo __('Action name:') ?></label></td>
        
        <td>
            <?php echo input_tag('filters[action_name]', isset($filters['action_name']) ? $filters['action_name'] : null, array (
  'size' => 15,
)) ?>
            
        </td>
               


        <td><label for="filters_url"><?php echo __('Url:') ?></label></td>
        
        <td>
            <?php echo input_tag('filters[url]', isset($filters['url']) ? $filters['url'] : null, array (
  'size' => 15,
)) ?>
            
        </td>
               


        <td><label for="filters_created_at"><?php echo __('Created at:') ?></label></td>
        
        <td>
            <?php echo input_date_range_tag('filters[created_at]', isset($filters['created_at']) ? $filters['created_at'] : null, array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
)) ?>
            
        </td>
               

</tr>
</thead>
</tbody>
</table>


<table cellspacing="0" border="0" class="sf_admin_list">
<thead>
<tr class="sf_admin_row_br_0_0" width="100%">
    <td align="right"><?php echo button_to(__('reset'), 'sfGuardUserLog/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></td>
    <td><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></td>
</tr>
</thead>
</tbody>
</table>
</div></div>
</form>
<!--*END Filters *-->
