<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/30 11:26:57
?>
<?php use_helper('I18N', 'Date') ?>


<div class="deal"><?php echo __('User Log list', 
array()) ?></div>


<?php include_partial('sfGuardUserLog/list_header', array('pager' => $pager)) ?>

<?php include_partial('filters', array('filters' => $filters)) ?>

<br />
<br />



<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('sfGuardUserLog/list', array('pager' => $pager)) ?>
<?php endif; ?>

<?php include_partial('sfGuardUserLog/list_footer', array('pager' => $pager)) ?>
