<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:08
?>
<?php use_helper('ObjectDoctrineAdmin', 'Object', 'Date') ?>

<?php echo form_tag('room/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($hotels_room, 'getid') ?>


<table>
<tbody>
<tr>
  <th>Hotels room type:</th>
  <td><?php echo select_tag(
          'hotels_room[HotelsRoomType]', 
          options_for_select($type, $hotels_room->type_id) 
          ) ?>
  </td>
</tr>
<tr>
  <th>Price: </th>
  <td><?php echo input_tag('hotels_room[price]', $hotels_room['price']) ?></td>
</tr>
<tr>
  <th>Photo: </th>
  <td><?php echo input_tag('hotels_room[photo]', $hotels_room['photo']) ?></td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($hotels_room->id): ?>
  &nbsp;<?php echo link_to('delete', 'room/delete?id='.$hotels_room->id, 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'room/show?id='.$hotels_room->id) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'room/list') ?>
<?php endif; ?>
</form>
