<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:08
?>
<h1>room</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>HotelsRoomType</th>
  <th>Price</th>
  <th>Photo</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($hotels_rooms as $hotels_room): ?>
  <tr>
    <td><?php echo $hotels_room->get('id'); ?></td>
    <td><?php echo $hotels_room->get('HotelsRoomType')->get('type'); ?></td>
    <td><?php vprintf('%01.2f', $hotels_room->get('price')/100); ?> $</td>
    <td><?php echo $hotels_room->get('photo'); ?></td>
    <td><?php echo $hotels_room->get('created_at'); ?></td>
    <td><?php echo $hotels_room->get('updated_at'); ?></td>
    <td>
        <?php echo link_to('open', 'room/show?id='.$hotels_room->id); ?>&nbsp;
        <?php echo link_to('edit', 'room/edit?id='.$hotels_room->id) ?>&nbsp;
        <?php echo link_to ('delete', 'room/delete?id='.$hotels_room->id) ?>
    </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
Number of hotels_rooms: <?php echo count($hotels_rooms) ?><br />
<?php echo link_to ('create', 'room/create') ?>
