<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:08
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $hotels_room->getid() ?></td>
</tr>
<tr>
<th>Hotels room type: </th>
<td><?php echo $hotels_room->getHotelsRoomType() ?></td>
</tr>
<tr>
<th>Price: </th>
<td><?php echo $hotels_room->getprice() ?></td>
</tr>
<tr>
<th>Photo: </th>
<td><?php echo $hotels_room->getphoto() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $hotels_room->getcreated_at() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $hotels_room->getupdated_at() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'room/edit?id='.$hotels_room->id) ?>
&nbsp;<?php echo link_to('list', 'room/list') ?>
