<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardModulesTable extends Doctrine_Table
{
  static public function retrieveByActionNameAndModuleName( $action_name, $module_name )
  {
    return Doctrine_Query::create()->from('sfGuardModules m')->where( 'm.action_name = ? AND m.module_name = ?', array( $action_name, $module_name ) )->execute()->getFirst();
  }
}