<?php
// auto-generated by sfDoctrineAdmin
// date: 2013/02/15 16:31:19
?>
<?php

/**
 * room_type actions.
 *
 * @package    sf_sandbox
 * @subpackage room_type
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Olivier Verdier <Olivier.Verdier@gmail.com>
 * @version    SVN: $Id: actions.class.php 5639 2007-10-23 14:27:18Z Eric.Fredj 
 */
class room_typeActions extends autoroom_typeActions{
    public function executeShow(){
        $room_type_id = (int) $this->getRequestParameter('id', 0);
        if(empty($room_type_id)){
            $this->setFlash('warning', 'Invalid room type id specified');
            $this->redirect('room_type');
        }
        $this->hotels_room_type = Doctrine::getTable('HotelsRoomType')
            ->find($room_type_id);
    }
}
