<?php
// auto-generated by sfDoctrineAdmin
// date: 2011/11/30 11:56:18
?>
<?php echo form_tag('sfGuardUser/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_guard_user, 'getid') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_guard_user[username]', __($labels['sf_guard_user{username}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{username}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{username}')): ?>
    <?php echo form_error('sf_guard_user{username}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'username',
  ),
), array (
  'control_name' => 'sf_guard_user[username]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[email_address]', __($labels['sf_guard_user{email_address}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{email_address}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{email_address}')): ?>
    <?php echo form_error('sf_guard_user{email_address}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'email_address',
  ),
), array (
  'control_name' => 'sf_guard_user[email_address]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
  
<div class="form-row">
  <?php echo label_for('sf_guard_user[phone]', __($labels['sf_guard_user{phone}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{phone}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{phone}')): ?>
    <?php echo form_error('sf_guard_user{phone}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'phone',
  ),
), array (
  'control_name' => 'sf_guard_user[phone]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[first_name]', __($labels['sf_guard_user{first_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{first_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{first_name}')): ?>
    <?php echo form_error('sf_guard_user{first_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'first_name',
  ),
), array (
  'control_name' => 'sf_guard_user[first_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[last_name]', __($labels['sf_guard_user{last_name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{last_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{last_name}')): ?>
    <?php echo form_error('sf_guard_user{last_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'last_name',
  ),
), array (
  'control_name' => 'sf_guard_user[last_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[password]', __($labels['sf_guard_user{password}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password}')): ?>
    <?php echo form_error('sf_guard_user{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password', array('type' => 'edit', 'sf_guard_user' => $sf_guard_user)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[password_bis]', __($labels['sf_guard_user{password_bis}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?>
    <?php echo form_error('sf_guard_user{password_bis}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password_bis', array('type' => 'edit', 'sf_guard_user' => $sf_guard_user)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_information" class="">
<h2><?php echo __('Information') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_user[last_login]', __($labels['sf_guard_user{last_login}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{last_login}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{last_login}')): ?>
    <?php echo form_error('sf_guard_user{last_login}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->last_login !== null && $sf_guard_user->last_login !== '') ? format_date($sf_guard_user->last_login, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[last_ip]', __($labels['sf_guard_user{last_ip}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{last_ip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{last_ip}')): ?>
    <?php echo form_error('sf_guard_user{last_ip}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_guard_user->last_ip; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[created_at]', __($labels['sf_guard_user{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{created_at}')): ?>
    <?php echo form_error('sf_guard_user{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->created_at !== null && $sf_guard_user->created_at !== '') ? format_date($sf_guard_user->created_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[updated_at]', __($labels['sf_guard_user{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{updated_at}')): ?>
    <?php echo form_error('sf_guard_user{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->updated_at !== null && $sf_guard_user->updated_at !== '') ? format_date($sf_guard_user->updated_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<div style="display: <?=($sf_user->getGuardUser()->getIsSuperAdmin() ? 'block' : 'none'); ?>;">

<fieldset id="sf_fieldset_permissions_and_groups" class="">
<h2><?php echo __('Permissions and Groups') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_user[is_active]', __($labels['sf_guard_user{is_active}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{is_active}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{is_active}')): ?>
    <?php echo form_error('sf_guard_user{is_active}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'is_active',
  ),
), array (
  'control_name' => 'sf_guard_user[is_active]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<?php if(count($sf_guard_user->groups) > 0): ?>
<div class="form-row">
  <?php echo label_for('sf_guard_user[groups]', __($labels['sf_guard_user{groups}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{groups}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{groups}')): ?>
    <?php echo form_error('sf_guard_user{groups}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>
  
  <?php $value = object_doctrine_admin_check_list($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'groups',
  ),
), array (
  'control_name' => 'sf_guard_user[groups]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
<?php endif;?>

<div class="form-row">
  <?php echo label_for('sf_guard_user[permissions]', __($labels['sf_guard_user{permissions}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{permissions}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{permissions}')): ?>
    <?php echo form_error('sf_guard_user{permissions}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_doctrine_admin_check_list($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'permissions',
  ),
), array (
  'control_name' => 'sf_guard_user[permissions]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>


</div>

<?php include_partial('edit_actions', array('sf_guard_user' => $sf_guard_user)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($sf_guard_user->id && $sf_user->getGuardUser()->getIsSuperAdmin()): ?>
<?php echo button_to(__('delete'), 'sfGuardUser/delete?id='.$sf_guard_user->id, array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
