HotelsAdmin:
  columns:
    email: { type: string(255), notnull: true, unique: true }
    password: { type: string(255), notnull: true, unique: true }
    created_at: { type: timestamp, notnull: true }
    updated_at: { type: timestamp, notnull: true }