HotelsAdmin:
  actAs: [ Timestampable ]
  columns:
    email:            { type: string(50), notnull: true, unique: true }
    password:         { type: string(32), notnull: true }
    last_loggedin_at: { type: timestamp }

HotelsClient:
  actAs: [ Timestampable ]
  columns:
    first_name: { type: string(100), notnull: true }
    last_name:  { type: string(100), notnull: true }
    email:      { type: string(50), notnull: true, unique: true }
    phone:      { type: string(20), notnull: true }
	
HotelsReservation:
  actAs: [ Timestampable ]
  columns:
    client_id:     { type: integer(11), notnull: true }
    room_id:       { type: integer(11), notnull: true }
    total:         { type: integer(11), notnull: true }
    hash:          { type: string(32), notnull: true }
    reserved_from: { type: timestamp, notnull: true }
    reserved_to:   { type: timestamp, notnull: true }
  relations:
    HotelsRoom:
      local:  room_id
      foreign:  id
    HotelsClient:
      local:  client_id
      foreign:  id
	
HotelsRoom:
  actAs: [ Timestampable ]
  columns:
    type_id:    { type: integer(11), notnull: true }
    price:      { type: integer(11), notnull: true }
    photo:      { type: string(200) }
  relations:
    HotelsRoomType:
      local:  type_id
      foreign:  id
  
HotelsRoomType:
  actAs: [ Timestampable ]
  columns:
    type: { type: string(200), notnull: true, unique: true }